define(
    'app/view/index',
    [
        'app/view/about/about.index',
        'app/view/abstract/abstract.index',
        'app/view/admin/admin.index',
        'app/view/home/home.index',
        'app/view/dashboard/dashboard.index',
        'app/view/app.view.module'
    ]
);